#!/usr/bin/env python3

import sys
import pickle



print("IS IT WORKING?????", file=sys.stderr)
print("IS IT WORKING????? stdout")

with open("clean.txt", "w") as file:
    file.write("It worked!")
    
with open("dirty.pkl", 'wb') as f:
    pickle.dump("It worked pickled!", f)
